AllCops:
  TargetRubyVersion: 2.4
Metrics:
  Enabled: true
  Exclude:
    - lib/truework/request.rb
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - truework.gemspec
Style/Documentation:
  Enabled: false
