# frozen_string_literal: true

require 'truework/resources/address'
require 'truework/resources/company'
require 'truework/resources/document'
require 'truework/resources/earnings'
require 'truework/resources/employee'
require 'truework/resources/employer'
require 'truework/resources/position'
require 'truework/resources/price'
require 'truework/resources/report'
require 'truework/resources/salary'
require 'truework/resources/target'
require 'truework/resources/turnaround_time'
require 'truework/resources/verification_request'
