name: CI

on:
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    name: Pre-release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: Install dependencies
      run: gem install bundler
    - name: Run Setup
      run: ./bin/setup
    - name: Lint
      run: rubocop
    - name: Test
      run: rake spec
